# Generated by Django 5.0.4 on 2024-11-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='Images')),
            ],
        ),
    ]
