# Generated by Django 5.0.4 on 2024-11-18 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='picked',
            field=models.BooleanField(default=False),
        ),
    ]
