# Generated by Django 5.0.4 on 2024-11-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_shoppinglist1_shoppingitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist1',
            name='picked',
            field=models.BooleanField(default=False),
        ),
    ]
