# Generated by Django 5.0.4 on 2024-12-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_shoppinglist1_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='save',
            field=models.CharField(default='Save 20', max_length=225),
        ),
    ]
