# Generated by Django 5.0.4 on 2024-12-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_product_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='save',
            new_name='sav',
        ),
    ]
