# Generated by Django 5.0.4 on 2025-02-22 10:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_save_product_sav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shoppingitem',
            name='shopping_list',
        ),
        migrations.DeleteModel(
            name='ShoppingListDownload',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='ShoppingItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList1',
        ),
    ]
